# Generated by Django 5.1.7 on 2025-03-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(max_length=20)),
                ('empName', models.CharField(max_length=100)),
                ('empEmail', models.EmailField(max_length=254)),
                ('empContact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'employee_new',
            },
        ),
    ]
