# Generated by Django 5.1.7 on 2025-03-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudOperation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='empContact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='empEmail',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='empId',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='empName',
        ),
    ]
